notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure:

# Language options
language: node_js
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: OkTH1xtjBnuW7S/eg4Oin1aQWCJfy0rHdVmxdh99YwHdhotgXSgXWhaTZwId63Czyqnih9YpCJ0+uOB0plGQQm7hQPnpLOYHeKZ1/SDQ9IJJgb/PTOFEsleFI7AoDmERGz/FAYGE7MRCEPHkZZE1QdKXV4y5HUWPG2bHpI5j2A3VyIZGqin2296GMbGCyFRzkVWYGMGQMtCUWOQ4NLT2IPwWnCsrQX4wgPD5L+R2CczylAp54N74iXjm6/zz+v1sKqh7j1MmvctCSeRw2LstozSickg8lWyBSQdsgUQ8UJcR/dxmCw0kIgb0PlHfnm6qAehcDxEMcPOTcu3vsix9Zxg2Vx5ILzJuWfNHtDQndzuFbmfeYU774sWqZ2cLbRTcEN1asIHPzKUsEo2sUsN58y3XTnPB9D7jndbUvzFkQvbHroCDY8xVTCHBeoIYVAr4+OeJd82yfhxuE45gR2Qrvinl14lshnhgS+f3WnNvdGjT6VU809Iu58YTzuskVKkauTvQoBVuxXISYfs9Dk+owg4PH9LSa0pluDPyyruWT6P4U9bodyTliPKsH18wvgXHgspaEvHshXsvPlASUqqmIjeVEpezg9pARSmunup+EujO98dcIFJYMWlSSzq58GQOAFGrRscMMkxzwZqzfMw2T192HW1FZUCTqwe98xk5lHg=
  on:
    node: 4
