notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: BlhvkvfKx723+i+VJi+2yY5qTMOIo+Onm/+fE4hYllascmirAxIOjWgHXXwW4FQIJUrL0zSCJxwDtUYanJTDydDgz+chi+q05IH3ULno9IZ26CXr2Z9vmrk0b+u7KT4N3IujFD6FhVDLcMxymgdtJ4Rn0R3SSTNBlGvP6VjCR5FTcqzCIbu4NTiE44gzq/N32JzzbdFIkf5PMIpQSzi6bZopAAyyJZRyrfUEyOm/ej3USDraLFjH9pVTSjUcBvm4ZlPr24mYW7uumASGNeXEie0fweXDscSc2KzdQT2ius3UykMsctoWGrm7wYiaLVrOmPcU9HTDTl8xMhn+xu93zMYSuzpvYHlu8lsb0Qw8I4QKS8rkgU/fn6gvS4wB8DBTT0NpxGPjWliKXc7zRuCm/6oLSbuOGf1ff5gKgghJK0poC4nOdeAu/gOfOOQSb1KPFpF/lFl2EdcU9MdTiV6qM0Fxg2xp+Zck00O1JXaWB1nSjrILvl9lL+dpKavoxa/i3yN0Uz6ujyHKDkORX6Sw1WwHw+5rVIptPTBNcutVEPY+oieh1GrLeUvk/gKELoBc8ethAi8uFUQENnPZh/ibqlw0Z7By4IvEswcQImGGL8ETKYVr2mTHIS5Sdp11xbwkUP/vzJdC9N8j8+yLzpl8sAV0FCdz9HYlYy3h28eMiSI=

# Language options
language: node_js
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: OkTH1xtjBnuW7S/eg4Oin1aQWCJfy0rHdVmxdh99YwHdhotgXSgXWhaTZwId63Czyqnih9YpCJ0+uOB0plGQQm7hQPnpLOYHeKZ1/SDQ9IJJgb/PTOFEsleFI7AoDmERGz/FAYGE7MRCEPHkZZE1QdKXV4y5HUWPG2bHpI5j2A3VyIZGqin2296GMbGCyFRzkVWYGMGQMtCUWOQ4NLT2IPwWnCsrQX4wgPD5L+R2CczylAp54N74iXjm6/zz+v1sKqh7j1MmvctCSeRw2LstozSickg8lWyBSQdsgUQ8UJcR/dxmCw0kIgb0PlHfnm6qAehcDxEMcPOTcu3vsix9Zxg2Vx5ILzJuWfNHtDQndzuFbmfeYU774sWqZ2cLbRTcEN1asIHPzKUsEo2sUsN58y3XTnPB9D7jndbUvzFkQvbHroCDY8xVTCHBeoIYVAr4+OeJd82yfhxuE45gR2Qrvinl14lshnhgS+f3WnNvdGjT6VU809Iu58YTzuskVKkauTvQoBVuxXISYfs9Dk+owg4PH9LSa0pluDPyyruWT6P4U9bodyTliPKsH18wvgXHgspaEvHshXsvPlASUqqmIjeVEpezg9pARSmunup+EujO98dcIFJYMWlSSzq58GQOAFGrRscMMkxzwZqzfMw2T192HW1FZUCTqwe98xk5lHg=
  on:
    node: 4
